# Generated by Django 4.1 on 2023-08-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0002_alter_adjustmentbalanceentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanceaccount',
            name='payable_type',
            field=models.CharField(choices=[('RP', 'Collected Royalties Payable to Customer'), ('AR', 'Service Fees Accounts Receivable')], max_length=2),
        ),
    ]
