# Generated by Django 4.1 on 2023-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0004_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdjustmentBalanceEntryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Balance Adjustment Entry',
                'verbose_name_plural': 'Balance Adjustment Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('earnings_dashboard_app.userbalanceentry',),
        ),
        migrations.CreateModel(
            name='UserEarningsBalanceEntryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Balance Earnings Entry',
                'verbose_name_plural': 'Balance Earnings Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('earnings_dashboard_app.userbalanceentry',),
        ),
        migrations.CreateModel(
            name='UserPaymentBalanceEntryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Balance Payment Entry',
                'verbose_name_plural': 'Balance Payment Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('earnings_dashboard_app.userbalanceentry',),
        ),
        migrations.AlterModelOptions(
            name='adjustmentbalanceentry',
            options={'verbose_name_plural': 'Balance Adjustment Entries'},
        ),
        migrations.AlterModelOptions(
            name='earningsbalanceentry',
            options={'verbose_name_plural': 'Balance Earnings Entries'},
        ),
        migrations.AlterModelOptions(
            name='paymentbalanceentry',
            options={'verbose_name_plural': 'Balance Payment Entries'},
        ),
        migrations.AlterField(
            model_name='userbalanceentry',
            name='invoice_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
