# Generated by Django 4.1 on 2023-08-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0005_useradjustmentbalanceentryproxy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earningsbalanceentry',
            old_name='incremental_amount',
            new_name='incremental_earnings',
        ),
        migrations.RenameField(
            model_name='earningsbalanceentry',
            old_name='total_amount',
            new_name='total_earnings',
        ),
    ]
