# Generated by Django 4.1 on 2023-08-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0008_serviceentity_entity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalanceentry',
            name='entry_type',
            field=models.CharField(choices=[('ARS', 'AR Earnings Service Fee'), ('ARP', 'AR Payment Received'), ('ARI', 'AR Balance Adjustment Increase'), ('ARD', 'AR Balance Adjustment Decrease'), ('RPE', 'RP Earnings Payable'), ('RPP', 'RP Payment Sent'), ('RPI', 'RP Balance Adjustment Increase'), ('RPD', 'RP Balance Adjustment Decrease')], default='ARS', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbalanceentry',
            name='user_balance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='earnings_dashboard_app.userbalanceaccount'),
        ),
    ]
