# Generated by Django 4.1 on 2023-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0009_userbalanceentry_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceadjustmententry',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancepaymententry',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
