# Generated by Django 4.1 on 2023-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0010_balanceadjustmententry_adjustment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalanceentry',
            name='entry_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balanceadjustmententry',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
