# Generated by Django 4.1 on 2023-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0011_userbalanceentry_entry_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanceentry',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='userbalanceentry',
            name='entry_type',
            field=models.CharField(choices=[('ARS', 'AR Earnings Service Fee'), ('ARP', 'AR Payment Received'), ('ARI', 'AR Balance Adjustment Increase'), ('ARD', 'AR Balance Adjustment Decrease'), ('RPE', 'RP Earnings Payable'), ('RPP', 'RP Payment Sent'), ('RPI', 'RP Balance Adjustment Increase'), ('RPD', 'RP Balance Adjustment Decrease')], editable=False, max_length=3),
        ),
    ]
