# Generated by Django 4.1 on 2023-08-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0012_alter_userbalanceentry_balance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanceentry',
            name='entry_detail',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbalanceentry',
            name='user_balance_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='earnings_dashboard_app.userbalanceaccount'),
            preserve_default=False,
        ),
    ]
