# Generated by Django 4.1 on 2023-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0013_alter_userbalanceentry_entry_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanceentry',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
