# Generated by Django 4.1 on 2023-08-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0014_alter_userbalanceentry_balance_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancepaymententry',
            old_name='entity_account_ref',
            new_name='bank_custom_name',
        ),
    ]
