# Generated by Django 4.1 on 2023-08-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0015_rename_entity_account_ref_balancepaymententry_bank_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalanceentry',
            name='user_display_status',
            field=models.CharField(choices=[('PN', 'PENDING - NOT RECONCILED'), ('PR', 'PENDING - RECONCILED'), ('VS', 'VISIBLE')], default='PN', max_length=2),
        ),
    ]
