# Generated by Django 4.1 on 2023-08-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0016_userbalanceentry_user_display_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceearningsentryproxy',
            options={'verbose_name': 'Balance Earnings Entry', 'verbose_name_plural': 'Balance Earnings Entries'},
        ),
        migrations.AlterModelOptions(
            name='userbalanceentry',
            options={'verbose_name_plural': 'User Balance Ledger'},
        ),
        migrations.RenameField(
            model_name='userbalanceentry',
            old_name='balance_amount',
            new_name='amount',
        ),
    ]
