# Generated by Django 4.1 on 2023-08-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0018_userbalanceaccount_balance_all_entries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbalanceaccount',
            name='balance_all_entries',
        ),
        migrations.RemoveField(
            model_name='userbalanceaccount',
            name='balance_displayed',
        ),
        migrations.RemoveField(
            model_name='userbalanceaccount',
            name='balance_reconciled',
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='user_report_files/')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_dashboard_app.reporttype')),
                ('user_balance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_dashboard_app.userbalanceaccount')),
            ],
        ),
    ]
