# Generated by Django 4.1 on 2023-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0019_reporttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanceentry',
            name='entry_type',
            field=models.CharField(choices=[('ARS', 'Billed Service Fee'), ('ARP', 'Payment Received for Service Fees'), ('ARI', 'AR Balance Adjustment Increase'), ('ARD', 'AR Balance Adjustment Decrease'), ('RPE', 'Net Royalties Payable'), ('RPP', 'Net Royalty Payment Sent'), ('RPI', 'RP Balance Adjustment Increase'), ('RPD', 'RP Balance Adjustment Decrease')], editable=False, max_length=3),
        ),
    ]
