# Generated by Django 4.1 on 2023-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0020_alter_userbalanceentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalanceentry',
            name='entry_type',
            field=models.CharField(choices=[('ARS', 'Billed Service Fee'), ('ARP', 'Service Fee Payment'), ('ARI', 'AR Balance Adjustment Increase'), ('ARD', 'AR Balance Adjustment Decrease'), ('RPE', 'Net Royalties Payable'), ('RPP', 'Net Royalty Payment'), ('RPI', 'RP Balance Adjustment Increase'), ('RPD', 'RP Balance Adjustment Decrease')], editable=False, max_length=3),
        ),
    ]
