# Generated by Django 4.2.5 on 2023-09-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_dashboard_app', '0021_alter_userbalanceentry_entry_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttype',
            options={'verbose_name': 'User Report Type', 'verbose_name_plural': 'User Report Types'},
        ),
        migrations.AlterModelOptions(
            name='userreport',
            options={'verbose_name': 'User Report', 'verbose_name_plural': 'User Reports'},
        ),
    ]
